version: '3.8'
services:
  app:
    container_name: pal
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 8211:8211/udp
    volumes:
      - ./Saved:/home/steam/ds/Pal/Saved
